import Footer from "@/components/ui/Footer";
import { Toaster } from "@/components/ui/toaster";
import { Metadata } from "next";
import { Suspense } from "react";
import Header from "./components/Header";
import SideSection from "./components/SideSection";
import SideSectionSkeleton from "./components/SideSectionSkeleton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="min-h-screen">
        <Header />
        <main className="mt-14 mb-14">
          <div className="max-w-screen-lg mx-auto lg:grid grid-cols-[calc(100%-300px)_300px]">
            {children}
            <Suspense fallback={<SideSectionSkeleton />}>
              <SideSection />
            </Suspense>
          </div>
          <Toaster />
        </main>
        <Footer />
      </div>
    </>
  );
}

export default Layout;
